version: '3'
services:
  strapi:
    container_name: strapi
    build: .
    restart: unless-stopped
    env_file: .env.docker
    volumes:
      - ./config:/opt/app/config
      - ./src:/opt/app/src
      - ./package.json:/opt/package.json
      - ./package-lock.json:/opt/package-lock.json
      - ./public/uploads:/opt/app/public/uploads
    ports:
      - 80:1337
    environment:
      DATABASE_SSL: false
    depends_on:
      - db
      - minio
    networks:
      - meilisearch
      - database
      - strapi
  db:
    image: postgres
    container_name: ${DATABASE_HOST}
    restart: always
    volumes:
      - strapi-data:/var/lib/postgresql/data/
    environment:
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    networks:
      - database
  meilisearch:
    container_name: 1j1s-meilisearch
    image: getmeili/meilisearch:v0.30.0
    environment:
      - MEILI_MASTER_KEY=${PLUGIN_MEILISEARCH_API_KEY:-masterKey}
      - MEILI_NO_ANALYTICS=${MEILI_NO_ANALYTICS:-true}
      - MEILI_ENV=${MEILI_ENV:-development}
      - MEILI_LOG_LEVEL=${MEILI_LOG_LEVEL:-trace}
      - MEILI_DB_PATH=${MEILI_DB_PATH:-/data.ms}
      - STRAPI_TELEMETRY_DISABLED=true
    networks:
      - meilisearch
    volumes:
      - meilisearch-data:/data.ms
    ports:
      - 7700:7700
    restart: unless-stopped
  createbuckets:
    image: minio/mc
    depends_on:
      - minio
    entrypoint: >
      /bin/sh -c "
      /usr/bin/mc config host add myminio http://minio:9000 ${MINIO_ACCESS_KEY} ${MINIO_SECRET_KEY};
      /usr/bin/mc rm -r --force myminio/${MINIO_BUCKET};
      /usr/bin/mc mb myminio/${MINIO_BUCKET};
      /usr/bin/mc policy download myminio/${MINIO_BUCKET};
      exit 0;
      "
    networks:
      - minio
  minio:
    image: minio/minio
    ports:
      - "9000:9000"
    volumes:
      - minio-data:/export
      - minio-config:/root/.minio
    environment:
      - MINIO_ROOT_USER=${MINIO_ACCESS_KEY}
      - MINIO_ROOT_PASSWORD=${MINIO_SECRET_KEY}
    networks:
      - strapi
      - minio
    command: server /export

networks:
  strapi:
    driver: bridge
  database:
    internal: true
  minio:
    internal: true

  meilisearch:
volumes:
  strapi-data:
  meilisearch-data:
  minio-data:
  minio-config:
