version: '3'
services:
  strapi:
    container_name: strapi
    build: .
    restart: unless-stopped
    env_file: .env.docker
    volumes:
      - ./config:/opt/app/config
      - ./src:/opt/app/src
      - ./package.json:/opt/package.json
      - ./package-lock.json:/opt/package-lock.json
      - ./public/uploads:/opt/app/public/uploads
    ports:
      - 80:1337
    environment:
      DATABASE_SSL: false
    depends_on:
      - db
    networks:
      - meilisearch
      - database
      - strapi
  db:
    image: postgres
    container_name: ${DATABASE_HOST}
    restart: always
    volumes:
      - strapi-data:/var/lib/postgresql/data/
    environment:
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    networks:
      - database
  meilisearch:
    container_name: 1j1s-meilisearch
    image: getmeili/meilisearch:v0.30.0
    environment:
      - MEILI_MASTER_KEY=${PLUGIN_MEILISEARCH_API_KEY:-masterKey}
      - MEILI_NO_ANALYTICS=${MEILI_NO_ANALYTICS:-true}
      - MEILI_ENV=${MEILI_ENV:-development}
      - MEILI_LOG_LEVEL=${MEILI_LOG_LEVEL:-trace}
      - MEILI_DB_PATH=${MEILI_DB_PATH:-/data.ms}
      - STRAPI_TELEMETRY_DISABLED=true
    networks:
      - meilisearch
    volumes:
      - meilisearch-data:/data.ms
    ports:
      - 7700:7700
    restart: unless-stopped
networks:
  strapi:
    driver: bridge
  database:
    internal: true
  meilisearch:
volumes:
  strapi-data:
  meilisearch-data:
