name: Publier la documentation sur les pages GitHub

on:
  push:
    branches:
      - main

jobs:
  build-docusaurus:
    name: Compiler Docusaurus
    runs-on: ubuntu-latest

    # All "run" step must be ran inside this subdirectory
    defaults:
      run:
        working-directory: docs

    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v5
        with:
          node-version-file: '.nvmrc'
          cache: npm

      - name: Installer les dépendances
        run: npm ci
        working-directory: docs

      - name: Compiler la documentation
        run: npm run build
        working-directory: docs

      - name: Téléverser les fichiers compilés Docusaurus
        uses: actions/upload-artifact@v4
        with:
          name: docusaurus
          path: ./docs/build

  deploy:
    name: Déployer sur GitHub Pages
    runs-on: ubuntu-latest
    needs: [ build-docusaurus ]

    steps:
      - name: Télécharger les fichiers Docusaurus
        uses: actions/download-artifact@v5
        with:
          name: docusaurus
          path: ./docs

      # Popular action to deploy to GitHub Pages:
      # Docs: https://github.com/peaceiris/actions-gh-pages#%EF%B8%8F-docusaurus
      - name: Déployer sur GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          # Build output to publish to the `gh-pages` branch:
          publish_dir: ./docs
          # The following lines assign commit authorship to the official
          # GH-Actions bot for deploys to `gh-pages` branch:
          # https://github.com/actions/checkout/issues/13#issuecomment-724415212
          # The GH actions bot is used by default if you didn't specify the two fields.
          # You can swap them out with your own user credentials.
          user_name: github-actions[bot]
          user_email: 41898282+github-actions[bot]@users.noreply.github.com
